### ISSUE TITLE
JSON::Type is undefined

### ISSUE THREAD

**Issue by christiankakesa** [lbguilherme/rethinkdb-lite#2]
JSON::Typpe is replaced by JSON::Any in new Crystal version.

```
in lib/rethinkdb-lite/src/reql/term.cr:50: undefined constant JSON::Type

        hash = Hash(String, JSON::Type).new
```

**Comment by lbguilherme** [comment]
Fixed. JSON::Type was removed as a breaking change on some Crystal release. This project now runs fine on Crystal 0.32.1 (latest as of now)
