### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by kingsleyh** [lbguilherme/rethinkdb-lite#3]
Hi - I still wanted to use rethinkdb with my project - so I've created a new project which is based on the other project https://github.com/cubos/rethinkdb.cr - but takes the user authentication from this project as the other one had much better api coverage

my repo is here: https://github.com/kingsleyh/crystal-rethinkdb - all the specs are passing and it's working with my project fine again :) - It was more of a quick patch up job - but at least it's working and with user authentication etc

**Comment by lbguilherme** [comment]
I started to give this project some love again. It's happening in my personal free time, but it should at least evolve. The short time goal is to increase API coverage and keep it working with latest Crystal/RethinkDB.

I'll be closing this, but feel free to get in touch.
